# Generated by Django 3.0.8 on 2020-08-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDidTusk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_false_percent', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leti.Student')),
                ('tusk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leti.Tusk')),
            ],
        ),
        migrations.AlterField(
            model_name='tusk',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leti.Teacher'),
        ),
    ]
