# Generated by Django 3.0.8 on 2020-08-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leti', '0002_auto_20200821_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAndAnswers',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_1_is', models.BooleanField()),
                ('answer_2', models.CharField(max_length=200)),
                ('answer_2_is', models.BooleanField()),
                ('answer_3', models.CharField(max_length=200)),
                ('answer_3_is', models.BooleanField()),
                ('answer_4', models.CharField(max_length=200)),
                ('answer_4_is', models.BooleanField()),
                ('answer_5', models.CharField(max_length=200)),
                ('answer_5_is', models.BooleanField()),
                ('answer_6', models.CharField(max_length=200)),
                ('answer_6_is', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='tusk',
            name='text',
            field=models.TextField(verbose_name='Текст задания'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Айди теста')),
                ('questions', models.ManyToManyField(to='leti.QuestionAndAnswers')),
            ],
        ),
    ]
