# Generated by Django 3.0.8 on 2020-08-26 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leti', '0004_auto_20200826_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('kol_user_true_answer', models.IntegerField(verbose_name='Колличество правильных ответов, которые сделал пользователь')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leti.Student')),
                ('tusk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leti.QuestionAndAnswers')),
            ],
        ),
    ]
