# Generated by Django 3.0.8 on 2020-08-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leti', '0005_testprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_or_not_1', models.BooleanField()),
                ('right_or_not_2', models.BooleanField()),
                ('right_or_not_3', models.BooleanField()),
                ('right_or_not_4', models.BooleanField()),
                ('right_or_not_5', models.BooleanField()),
                ('right_or_not_6', models.BooleanField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leti.Student')),
                ('tusk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leti.QuestionAndAnswers')),
            ],
        ),
    ]
