# Generated by Django 3.0.8 on 2020-08-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leti', '0006_passquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passquestion',
            name='right_or_not_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passquestion',
            name='right_or_not_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passquestion',
            name='right_or_not_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passquestion',
            name='right_or_not_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passquestion',
            name='right_or_not_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passquestion',
            name='right_or_not_6',
            field=models.BooleanField(default=False),
        ),
    ]
